const SUPER_ADMIN = 0
const OFFICER_STAFF = 1
const WAREHOUSE_STAFF = 2

const CREATED = 0
const ON_GOING = 1
const SUCCESS = 2
const FAILED = 3

const TRANSACTION_IN = 0
const TRANSACTION_OUT = 1

export default {SUPER_ADMIN, OFFICER_STAFF, WAREHOUSE_STAFF, CREATED, ON_GOING, SUCCESS, FAILED, TRANSACTION_IN, TRANSACTION_OUT}